# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  - sbt compile
